/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    class: Class;
    topics: Topic;
    cREQuestion: CREQuestion;
    englishQuestion: EnglishQuestion;
    socialStudiesQuestion: SocialStudiesQuestion;
    kiswahiliQuestion: KiswahiliQuestion;
    mathsQuestion: MathsQuestion;
    scienceQuestion: ScienceQuestion;
    media: Media;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class".
 */
export interface Class {
  id: number;
  Class?: string | null;
  'Class Image'?: number | Media | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  'Topic Image'?: number | Media | null;
  Topic?: string | null;
  Subject?:
    | (
        | 'cREQuestion'
        | 'englishQuestion'
        | 'geographyQuestion'
        | 'kiswahiliQuestion'
        | 'mathsQuestion'
        | 'scienceQuestion'
      )
    | null;
  Class?: {
    relationTo: 'class';
    value: number | Class;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cREQuestion".
 */
export interface CREQuestion {
  id: number;
  'Question Image'?: number | Media | null;
  Question?: string | null;
  answerone?: string | null;
  answertwo?: string | null;
  answerthree?: string | null;
  answerfour?: string | null;
  Class?: {
    relationTo: 'class';
    value: number | Class;
  } | null;
  Topic?: {
    relationTo: 'topics';
    value: number | Topic;
  } | null;
  'Right Answer'?: ('answerone' | 'answertwo' | 'answerthree' | 'answerfour') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "englishQuestion".
 */
export interface EnglishQuestion {
  id: number;
  'Question Image'?: number | Media | null;
  Question?: string | null;
  answerone?: string | null;
  answertwo?: string | null;
  answerthree?: string | null;
  answerfour?: string | null;
  Class?: {
    relationTo: 'class';
    value: number | Class;
  } | null;
  Topic?: {
    relationTo: 'topics';
    value: number | Topic;
  } | null;
  'Right Answer'?: ('answerone' | 'answertwo' | 'answerthree' | 'answerfour') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialStudiesQuestion".
 */
export interface SocialStudiesQuestion {
  id: number;
  'Question Image'?: number | Media | null;
  Question?: string | null;
  answerone?: string | null;
  answertwo?: string | null;
  answerthree?: string | null;
  answerfour?: string | null;
  Class?: {
    relationTo: 'class';
    value: number | Class;
  } | null;
  Topic?: {
    relationTo: 'topics';
    value: number | Topic;
  } | null;
  'Right Answer'?: ('answerone' | 'answertwo' | 'answerthree' | 'answerfour') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kiswahiliQuestion".
 */
export interface KiswahiliQuestion {
  id: number;
  'Question Image'?: number | Media | null;
  Question?: string | null;
  answerone?: string | null;
  answertwo?: string | null;
  answerthree?: string | null;
  answerfour?: string | null;
  Class?: {
    relationTo: 'class';
    value: number | Class;
  } | null;
  Topic?: {
    relationTo: 'topics';
    value: number | Topic;
  } | null;
  'Right Answer'?: ('answerone' | 'answertwo' | 'answerthree' | 'answerfour') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mathsQuestion".
 */
export interface MathsQuestion {
  id: number;
  'Question Image'?: number | Media | null;
  Question?: string | null;
  answerone?: string | null;
  answertwo?: string | null;
  answerthree?: string | null;
  answerfour?: string | null;
  Class?: {
    relationTo: 'class';
    value: number | Class;
  } | null;
  Topic?: {
    relationTo: 'topics';
    value: number | Topic;
  } | null;
  'Right Answer'?: ('answerone' | 'answertwo' | 'answerthree' | 'answerfour') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scienceQuestion".
 */
export interface ScienceQuestion {
  id: number;
  'Question Image'?: number | Media | null;
  Question?: string | null;
  answerone?: string | null;
  answertwo?: string | null;
  answerthree?: string | null;
  answerfour?: string | null;
  Class?: {
    relationTo: 'class';
    value: number | Class;
  } | null;
  Topic?: {
    relationTo: 'topics';
    value: number | Topic;
  } | null;
  'Right Answer'?: ('answerone' | 'answertwo' | 'answerthree' | 'answerfour') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}